-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@74.97Hz",
    position = "-1920x-10",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1200@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
