source = ./cfg/monitors.conf
source = ./cfg/keybinds.conf
source = ./cfg/input.conf
source = ./cfg/autostart.conf
source = ./cfg/env.conf
source = ./cfg/appearance.conf
source = ./cfg/layout.conf
source = ./cfg/misc.conf
source = ./cfg/rules.conf
