[pyprland]
plugins = ["scratchpads"]
notification_type = "auto"

[scratchpads.term]
command = "uwsm app -- kitty --class pypr-term --title Pypr-Terminal"
class = "pypr-term"
animation = "fromTop"
size = "80% 60%"
margin = 40
lazy = true
multi = false
smart_focus = true
process_tracking = false
