# | Auto Start |
# autostart your favorite applications here

exec-once = noctalia &

# Only to show the keybinds in your first session
exec-once = sleep 3 && noctalia msg panel-toggle kenn/keybind-cheatsheet:cheatsheet
exec-once = until busctl --user status org.kde.StatusNotifierWatcher >/dev/null 2>&1; do sleep 0.5; done; copyq