# | Input Devices |
# Configure your input devices here. | https://mangowm.github.io/docs/configuration/input

# xkb_rules_layout = us

# If you want to disable pointer acceleration, uncomment the lines below.
# accel_profile = 1
# accel_speed = 0.2

trackpad_natural_scrolling = 1
# mouse_natural_scrolling = 1
