# | Miscellaneous |
# https://mangowm.github.io/docs/configuration/miscellaneous

allow_tearing = 2
sync_obj_enable = 1
# xwayland_persistence = 1

drag_tile_to_tile = 1

# Hot corner: toggle overview | https://mangowm.github.io/docs/window-management/overview
# Corners: 0 top-left, 1 top-right, 2 bottom-left, 3 bottom-right
enable_hotarea = 1
hotarea_corner = 0
