# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

window_rule = is_floating:1, app_id:[Ss]team
window_rule = is_floating:0, title:Steam
window_rule = is_floating:1, app_id:steam, title:Steam Settings

layer_rule = no_animation:1, no_blur:1, layer_name:selection
