[main]
term=xterm-256color
font=MapleMono NF:size=10
pad=0x0 center

[scrollback]
lines=100000
indicator-format=percentage

[desktop-notifications]
# Requires notify-send.
command=notify-send --app-name="foot" --urgency=normal "${title}" "${body}"

[mouse]
hide-when-typing=yes
